package cmd

import (
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

// docsCmd represents the docs command
var docsCmd = &cobra.Command{
	Use:   "docs",
	Args:  cobra.NoArgs,
	Short: "Generate documentation for cloudtail",
	Long: `The docs command generates a complete documentation for cloudtail. 

By default, documentation files are be generated in the ./docs directory.
You can override the output directory using the --dir flag.

Markdown files are generated by default. Use the --format flag to specify a different output format.
The supported output formats are Markdown, man, rest and YAML.`,
	RunE: docsRun,
}

func docsRun(cmd *cobra.Command, args []string) error {
	if len(args) != 0 {
		return fmt.Errorf("docs takes no arguments")
	}

	defaultDir := "./docs"
	defaultFormat := "markdown"

	rootCmd.DisableAutoGenTag = true

	dir, err := cmd.Flags().GetString("dir")
	if err != nil {
		return fmt.Errorf("error parsing --dir flag: /n%w", err)
	}
	if dir != "" {
		defaultDir = dir
	}

	format, err := cmd.Flags().GetString("format")
	if err != nil {
		return fmt.Errorf("error parsing --format flag: /n%w", err)
	}
	if format != "" {
		defaultFormat = format
	}

	err = os.MkdirAll(defaultDir, 0755)
	if err != nil {
		return fmt.Errorf("error creating the documentation directory: /n%w", err)
	}

	switch defaultFormat {
	case "markdown":
		if err := doc.GenMarkdownTree(rootCmd, defaultDir); err != nil {
			return fmt.Errorf("error generating documentation: /n%w", err)
		}
	case "man":
		header := &doc.GenManHeader{Title: strings.ToUpper(rootCmd.Name()), Section: "1"}
		if err := doc.GenManTree(rootCmd, header, defaultDir); err != nil {
			return fmt.Errorf("error generating documentation: /n%w", err)
		}
	case "rest":
		if err := doc.GenReSTTree(rootCmd, defaultDir); err != nil {
			return fmt.Errorf("error generating documentation: /n%w", err)
		}
	case "yaml":
		if err := doc.GenYamlTree(rootCmd, defaultDir); err != nil {
			return fmt.Errorf("error generating documentation: /n%w", err)
		}
	default:
		return fmt.Errorf("unknown output format: /n%s", defaultFormat)
	}

	_, err = fmt.Fprintf(os.Stdout, "Documentation successfully created in %s\n", defaultDir)
	if err != nil {
		return err
	}

	return nil
}

func init() {
	rootCmd.AddCommand(docsCmd)

	docsCmd.Flags().StringP("dir", "d", "", "Destination directory for the documentation")
	docsCmd.Flags().StringP("format", "f", "", "Format of the documentation (markdown, man, rest, yaml)")
}
